"""Agregar username, email opcional

Revision ID: 044ad881981f
Revises: 58d2ea02f0d9
Create Date: 2026-06-19 21:19:16.837589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044ad881981f'
down_revision = '58d2ea02f0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False, server_default='temp'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_unique_constraint('uq_usuarios_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_username', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
