"""Migracion inicial: usuarios, roles, distritos, centros de salud y tablas relacionadas

Revision ID: 58d2ea02f0d9
Revises: 
Create Date: 2026-06-19 21:03:53.394790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d2ea02f0d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('poblacion_total', sa.Integer(), nullable=True),
    sa.Column('superficie_km2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_centro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('centros_salud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_centro_id', sa.Integer(), nullable=False),
    sa.Column('distrito_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['distrito_id'], ['distritos.id'], ),
    sa.ForeignKeyConstraint(['tipo_centro_id'], ['tipos_centro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cobertura_sanitaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distrito_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.Column('num_centros', sa.Integer(), nullable=True),
    sa.Column('indice_cobertura', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['distrito_id'], ['distritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('distrito_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distrito_id'], ['distritos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('centro_especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centro_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['centro_id'], ['centros_salud.id'], ),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centro_id', 'especialidad_id', name='uq_centro_especialidad')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('centro_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['centro_id'], ['centros_salud.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('centro_especialidad')
    op.drop_table('usuarios')
    op.drop_table('cobertura_sanitaria')
    op.drop_table('centros_salud')
    op.drop_table('tipos_centro')
    op.drop_table('especialidades')
    op.drop_table('roles')
    op.drop_table('distritos')
    # ### end Alembic commands ###
